# Generated by Django 2.1.1 on 2018-09-14 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radius', models.CharField(max_length=20)),
                ('initial_lat', models.FloatField()),
                ('initial_lon', models.FloatField()),
                ('index', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='coordinate',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalcenter.Result'),
        ),
    ]
